set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR mips32)

set(CMAKE_C_COMPILER mipsel-linux-musl-gcc)
set(CMAKE_CXX_COMPILER mipsel-linux-musl-g++)

set(CMAKE_FIND_ROOT_PATH /opt/brick/mipsel-linux-musl/sysroot)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)